name: PR-Checks

on: [pull_request]

jobs:
  pr-checks:
    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Check line endings
      uses: erclu/check-crlf@v1

    - name: Check code formatting
      uses: jidicula/clang-format-action@v4.10.2
      with:
          clang-format-version: '10'
          check-path: '.'
          exclude-regex: '(build/.*|_dependencies/.*)'
          include-regex: '.*\.(cpp|hpp|c|h)$'
